import * as types from "../../../_constants/ActionType";
var initialState = [
  {
    id: 2,
    user_id: 27,
    category: 1,
    shipping: 1,
    review: 2000,
    textBouns: "Nhận bộ quà hấp dẫn đến 8.5 triệu laptop 1",
    sale: 10,
    priceSeller1: 18000,
    price1: 20000,
    textkm: "",
    core: "i5- 7200U",
    pin: 10,
    ram: 4,
    ssd: 256,
    name:
      "2 Combo 4 Hộp Khẩu Trang Y Tế 3Hmask 3 Lớp Quai Bản (Trắng) không đau tai",
    preorder: "Đặt hàng trước ngày 12/ 01",
    picAlt:
      "Laptop Lenovo IdeaPad S340 14IIL i5 1035G1/8GB/512GB/Win10 (81VV003SVN)",
    link:
      "https://res.cloudinary.com/cv-thav-herokuapp-com/image/upload/v1616828464/laptop/sitdrw8fw9m6dmbwnvjf.jpg",

    categoryBeadcrumb: "Laptop",
    companyBeadcrumb: "Lenovo",
    cpuDetail: "Intel Core i5 Ice Lake, 1035G1, 1.00 GHz",
    ramDetail: "8 GB, DDR4 (On board 4GB +1 khe 4GB), 2666 MHz",
    ssdDetail: "SSD 512 GB M.2 PCIe, Hỗ trợ khe cắm HDD SATA",
    lcdDetail: "14 inch, Full HD (1920 x 1080)",
    vgaDetail: "Card đồ họa tích hợp, Intel UHD Graphics",
    inputDetail: "2 x USB 3.1, HDMI, USB Type-C",
    winDetail: "Windows 10 Home SL",
    settingDetail: "Vỏ nhựa - nắp lưng bằng kim loại, PIN liền",
    sizeDetail: "Dày 17.9 mm, 1.6 kg",
    years: 2019,
  },
  {
    id: 3,
    user_id: 27,
    category: 2,
    review: 2000,
    textBouns: "Nhận bộ quà hấp dẫn đến 8.5 triệu laptop 1",
    sale: 0,
    priceSeller1: 400000,
    price1: 500000,
    textkm: "",
    core: "i5- 7200U",
    pin: 10,
    ram: 4,
    ssd: 256,
    name:
      "3 Combo 4 Hộp Khẩu Trang Y Tế 3Hmask 3 Lớp Quai Bản (Trắng) không đau tai",
    preorder: "Đặt hàng trước ngày 12/ 01",
    picAlt:
      "Laptop Lenovo IdeaPad S340 14IIL i5 1035G1/8GB/512GB/Win10 (81VV003SVN)",
    link:
      "https://res.cloudinary.com/cv-thav-herokuapp-com/image/upload/v1616828464/laptop/co2zoy5u5zr1otgunu50.jpg",

    categoryBeadcrumb: "Laptop",
    companyBeadcrumb: "Lenovo",
    cpuDetail: "Intel Core i5 Ice Lake, 1035G1, 1.00 GHz",
    ramDetail: "8 GB, DDR4 (On board 4GB +1 khe 4GB), 2666 MHz",
    ssdDetail: "SSD 512 GB M.2 PCIe, Hỗ trợ khe cắm HDD SATA",
    lcdDetail: "14 inch, Full HD (1920 x 1080)",
    vgaDetail: "Card đồ họa tích hợp, Intel UHD Graphics",
    inputDetail: "2 x USB 3.1, HDMI, USB Type-C",
    winDetail: "Windows 10 Home SL",
    settingDetail: "Vỏ nhựa - nắp lưng bằng kim loại, PIN liền",
    sizeDetail: "Dày 17.9 mm, 1.6 kg",
    years: 2019,
  },
  {
    id: 27,
    user_id: 27,
    category: 1,
    review: 1000,
    textBouns: "Nhận bộ quà hấp dẫn đến 8.5 triệu laptop 2",
    sale: 10,
    priceSeller1: 180000,
    price1: 190000,
    textkm: "Hàng sắp về",
    core: "i5-7200U",
    pin: 100,
    ram: 40,
    ssd: 2560,
    name:
      "4 Combo 4 Hộp Khẩu Trang Y Tế 3Hmask 3 Lớp Quai Bản (Trắng) không đau tai",
    preorder: "Đặt hàng trước ngày 12/ 01",
    picAlt: "Samsung Galaxy S Mới 2",
    link:
      "https://res.cloudinary.com/cv-thav-herokuapp-com/image/upload/v1616828464/laptop/otgji5h257xhu6wwrz4j.jpg",

    categoryBeadcrumb: "Laptop",
    companyBeadcrumb: "Acer",
    cpuDetail: "2 Intel Core i5 Ice Lake, 1035G1, 1.00 GHz",
    ramDetail: "8 GB, DDR4 (On board 4GB +1 khe 4GB), 2666 MHz",
    ssdDetail: "SSD 512 GB M.2 PCIe, Hỗ trợ khe cắm HDD SATA",
    lcdDetail: "14 inch, Full HD (1920 x 1080)",
    vgaDetail: "Card đồ họa tích hợp, Intel UHD Graphics",
    inputDetail: "2 x USB 3.1, HDMI, USB Type-C",
    winDetail: "Windows 10 Home SL",
    settingDetail: "Vỏ nhựa - nắp lưng bằng kim loại, PIN liền",
    sizeDetail: "Dày 17.9 mm, 1.6 kg",
    years: 2019,
  },
  {
    id: 819,
    user_id: 27,
    category: 1,
    review: 2000,
    textBouns: "Nhận bộ quà hấp dẫn đến 8.5 triệu",
    sale: 0,
    priceSeller1: 5490000,
    price1: 5490000,
    textkm: "Hàng sắp về",
    core: "i5- 7200U",
    pin: 10,
    ram: 4,
    ssd: 256,
    name:
      "819 Combo 4 Hộp Khẩu Trang Y Tế 3Hmask 3 Lớp Quai Bản (Trắng) không đau tai",
    preorder: "Đặt hàng trước ngày 12/ 01",
    picAlt: "Samsung Galaxy S Mới 2",
    link:
      "https://res.cloudinary.com/cv-thav-herokuapp-com/image/upload/v1616828465/laptop/obg6kzjjy5oegcb4x5di.jpg",

    categoryBeadcrumb: "Laptop",
    companyBeadcrumb: "Apple",
    cpuDetail: "3 Intel Core i5 Ice Lake, 1035G1, 1.00 GHz",
    ramDetail: "8 GB, DDR4 (On board 4GB +1 khe 4GB), 2666 MHz",
    ssdDetail: "SSD 512 GB M.2 PCIe, Hỗ trợ khe cắm HDD SATA",
    lcdDetail: "14 inch, Full HD (1920 x 1080)",
    vgaDetail: "Card đồ họa tích hợp, Intel UHD Graphics",
    inputDetail: "2 x USB 3.1, HDMI, USB Type-C",
    winDetail: "Windows 10 Home SL",
    settingDetail: "Vỏ nhựa - nắp lưng bằng kim loại, PIN liền",
    sizeDetail: "Dày 17.9 mm, 1.6 kg",
    years: 2019,
  },
  {
    id: 820,
    user_id: 27,
    category: 3,
    review: 2000,
    textBouns: "Nhận bộ quà hấp dẫn đến 8.5 triệu",
    sale: 0,
    priceSeller1: 6950000,
    price1: 7490000,
    textkm: "Hàng sắp về",
    core: "i5- 7200U",
    pin: 10,
    ram: 4,
    ssd: 256,
    name:
      "820 Combo 4 Hộp Khẩu Trang Y Tế 3Hmask 3 Lớp Quai Bản (Trắng) không đau tai",
    preorder: "Đặt hàng trước ngày 12/ 01",
    picAlt:
      "Laptop Lenovo IdeaPad S340 14IIL i5 1035G1/8GB/512GB/Win10 (81VV003SVN)",
    link:
      "https://res.cloudinary.com/cv-thav-herokuapp-com/image/upload/v1616828465/laptop/chuqgc5o5acn8jojt4tn.jpg",
    categoryBeadcrumb: "Laptop",
    companyBeadcrumb: "Lenovo",
    cpuDetail: "Intel Core i5 Ice Lake, 1035G1, 1.00 GHz",
    ramDetail: "8 GB, DDR4 (On board 4GB +1 khe 4GB), 2666 MHz",
    ssdDetail: "SSD 512 GB M.2 PCIe, Hỗ trợ khe cắm HDD SATA",
    lcdDetail: "14 inch, Full HD (1920 x 1080)",
    vgaDetail: "Card đồ họa tích hợp, Intel UHD Graphics",
    inputDetail: "2 x USB 3.1, HDMI, USB Type-C",
    winDetail: "Windows 10 Home SL",
    settingDetail: "Vỏ nhựa - nắp lưng bằng kim loại, PIN liền",
    sizeDetail: "Dày 17.9 mm, 1.6 kg",
    years: 2019,
  },
  {
    id: 821,
    user_id: 27,
    category: 3,
    review: 1000,
    textBouns: "Nhận bộ quà hấp dẫn đến 8.5 triệu",
    sale: 0,
    priceSeller1: 2950000,
    price1: 4490000,
    textkm: "Hàng sắp về",
    core: "i5- 7200U",
    pin: 10,
    ram: 4,
    ssd: 256,
    name:
      "821 Combo 4 Hộp Khẩu Trang Y Tế 3Hmask 3 Lớp Quai Bản (Trắng) không đau tai",
    preorder: "Đặt hàng trước ngày 12/ 01",
    picAlt: "Samsung Galaxy S Mới 2",
    link:
      "https://res.cloudinary.com/cv-thav-herokuapp-com/image/upload/v1616828465/laptop/pjklm1lwycygumiicpjb.jpg",
    categoryBeadcrumb: "Laptop",
    companyBeadcrumb: "Acer",
    cpuDetail: "Intel Core i5 Ice Lake, 1035G1, 1.00 GHz",
    ramDetail: "8 GB, DDR4 (On board 4GB +1 khe 4GB), 2666 MHz",
    ssdDetail: "SSD 512 GB M.2 PCIe, Hỗ trợ khe cắm HDD SATA",
    lcdDetail: "14 inch, Full HD (1920 x 1080)",
    vgaDetail: "Card đồ họa tích hợp, Intel UHD Graphics",
    inputDetail: "2 x USB 3.1, HDMI, USB Type-C",
    winDetail: "Windows 10 Home SL",
    settingDetail: "Vỏ nhựa - nắp lưng bằng kim loại, PIN liền",
    sizeDetail: "Dày 17.9 mm, 1.6 kg",
    years: 2019,
  },
  {
    id: 822,
    user_id: 27,
    category: 0,
    review: 1000,
    textBouns: "Nhận bộ quà hấp dẫn đến 8.5 triệu",
    sale: 10,
    priceSeller1: 5950000,
    price1: 7490000,
    textkm: "Hàng sắp về",
    core: "i5- 7200U",
    pin: 10,
    ram: 4,
    ssd: 256,
    name:
      "822 Combo 4 Hộp Khẩu Trang Y Tế 3Hmask 3 Lớp Quai Bản (Trắng) không đau tai",
    preorder: "Đặt hàng trước ngày 12/ 01",
    picAlt: "Samsung Galaxy S Mới 2",
    link:
      "https://res.cloudinary.com/cv-thav-herokuapp-com/image/upload/v1616828465/laptop/pjklm1lwycygumiicpjb.jpg",
    categoryBeadcrumb: "Laptop",
    companyBeadcrumb: "Acer",
    cpuDetail: "Intel Core i5 Ice Lake, 1035G1, 1.00 GHz",
    ramDetail: "8 GB, DDR4 (On board 4GB +1 khe 4GB), 2666 MHz",
    ssdDetail: "SSD 512 GB M.2 PCIe, Hỗ trợ khe cắm HDD SATA",
    lcdDetail: "14 inch, Full HD (1920 x 1080)",
    vgaDetail: "Card đồ họa tích hợp, Intel UHD Graphics",
    inputDetail: "2 x USB 3.1, HDMI, USB Type-C",
    winDetail: "Windows 10 Home SL",
    settingDetail: "Vỏ nhựa - nắp lưng bằng kim loại, PIN liền",
    sizeDetail: "Dày 17.9 mm, 1.6 kg",
    years: 2019,
  },
  {
    id: 823,
    user_id: 27,
    category: 3,
    review: 2000,
    textBouns: "Nhận bộ quà hấp dẫn đến 8.5 triệu",
    sale: 10,
    priceSeller1: 18950000,
    price1: 23490000,
    textkm: "Hàng sắp về",
    core: "i5- 7200U",
    pin: 10,
    ram: 4,
    ssd: 256,
    name:
      "823 Combo 4 Hộp Khẩu Trang Y Tế 3Hmask 3 Lớp Quai Bản (Trắng) không đau tai",
    preorder: "Đặt hàng trước ngày 12/ 01",
    picAlt: "Samsung Galaxy S Mới 2",
    link:
      "https://res.cloudinary.com/cv-thav-herokuapp-com/image/upload/v1616828464/laptop/otgji5h257xhu6wwrz4j.jpg",
    categoryBeadcrumb: "Laptop",
    companyBeadcrumb: "Acer",
    cpuDetail: "Intel Core i5 Ice Lake, 1035G1, 1.00 GHz",
    ramDetail: "8 GB, DDR4 (On board 4GB +1 khe 4GB), 2666 MHz",
    ssdDetail: "SSD 512 GB M.2 PCIe, Hỗ trợ khe cắm HDD SATA",
    lcdDetail: "14 inch, Full HD (1920 x 1080)",
    vgaDetail: "Card đồ họa tích hợp, Intel UHD Graphics",
    inputDetail: "2 x USB 3.1, HDMI, USB Type-C",
    winDetail: "Windows 10 Home SL",
    settingDetail: "Vỏ nhựa - nắp lưng bằng kim loại, PIN liền",
    sizeDetail: "Dày 17.9 mm, 1.6 kg",
    years: 2019,
  },
  {
    id: 824,
    user_id: 27,
    category: 3,
    review: 1000,
    textBouns: "Nhận bộ quà hấp dẫn đến 8.5 triệu",
    sale: 0,
    priceSeller1: 12950000,
    price1: 23490000,
    textkm: "Hàng sắp về",
    core: "i5- 7200U",
    pin: 10,
    ram: 4,
    ssd: 256,
    name:
      "824 Combo 4 Hộp Khẩu Trang Y Tế 3Hmask 3 Lớp Quai Bản (Trắng) không đau tai",
    preorder: "Đặt hàng trước ngày 12/ 01",
    picAlt: "Samsung Galaxy S Mới 2",
    link:
      "https://res.cloudinary.com/cv-thav-herokuapp-com/image/upload/v1616828464/laptop/h1fdq9hepckbfkea7yq7.jpg",
    categoryBeadcrumb: "Laptop",
    companyBeadcrumb: "Acer",
    cpuDetail: "Intel Core i5 Ice Lake, 1035G1, 1.00 GHz",
    ramDetail: "8 GB, DDR4 (On board 4GB +1 khe 4GB), 2666 MHz",
    ssdDetail: "SSD 512 GB M.2 PCIe, Hỗ trợ khe cắm HDD SATA",
    lcdDetail: "14 inch, Full HD (1920 x 1080)",
    vgaDetail: "Card đồ họa tích hợp, Intel UHD Graphics",
    inputDetail: "2 x USB 3.1, HDMI, USB Type-C",
    winDetail: "Windows 10 Home SL",
    settingDetail: "Vỏ nhựa - nắp lưng bằng kim loại, PIN liền",
    sizeDetail: "Dày 17.9 mm, 1.6 kg",
    years: 2019,
  },
  {
    id: 825,
    user_id: 27,
    category: 1,
    review: 1000,
    textBouns: "Nhận bộ quà hấp dẫn đến 8.5 triệu",
    sale: 10,
    priceSeller1: 14950000,
    price1: 15490000,
    textkm: "Hàng sắp về",
    core: "i5- 7200U",
    pin: 10,
    ram: 4,
    ssd: 256,
    name:
      "825 Combo 4 Hộp Khẩu Trang Y Tế 3Hmask 3 Lớp Quai Bản (Trắng) không đau tai",
    preorder: "Đặt hàng trước ngày 12/ 01",
    picAlt: "Samsung Galaxy S Mới 2",
    link:
      "https://res.cloudinary.com/cv-thav-herokuapp-com/image/upload/v1616828464/laptop/co2zoy5u5zr1otgunu50.jpg",
    categoryBeadcrumb: "Laptop",
    companyBeadcrumb: "Acer",
    cpuDetail: "Intel Core i5 Ice Lake, 1035G1, 1.00 GHz",
    ramDetail: "8 GB, DDR4 (On board 4GB +1 khe 4GB), 2666 MHz",
    ssdDetail: "SSD 512 GB M.2 PCIe, Hỗ trợ khe cắm HDD SATA",
    lcdDetail: "14 inch, Full HD (1920 x 1080)",
    vgaDetail: "Card đồ họa tích hợp, Intel UHD Graphics",
    inputDetail: "2 x USB 3.1, HDMI, USB Type-C",
    winDetail: "Windows 10 Home SL",
    settingDetail: "Vỏ nhựa - nắp lưng bằng kim loại, PIN liền",
    sizeDetail: "Dày 17.9 mm, 1.6 kg",
    years: 2019,
  },

  {
    id: 826,
    user_id: 27,
    category: 1,
    review: 1000,
    textBouns: "Nhận bộ quà hấp dẫn đến 8.5 triệu",
    sale: 10,
    priceSeller1: 11950000,
    price1: 23490000,
    textkm: "Hàng sắp về",
    core: "i5- 7200U",
    pin: 10,
    ram: 4,
    ssd: 256,
    name:
      "826 Combo 4 Hộp Khẩu Trang Y Tế 3Hmask 3 Lớp Quai Bản (Trắng) không đau tai",
    preorder: "Đặt hàng trước ngày 12/ 01",
    picAlt: "Samsung Galaxy S Mới 2",
    link:
      "https://res.cloudinary.com/cv-thav-herokuapp-com/image/upload/v1616828464/laptop/h1fdq9hepckbfkea7yq7.jpg",
    categoryBeadcrumb: "Laptop",
    companyBeadcrumb: "Acer",
    cpuDetail: "Intel Core i5 Ice Lake, 1035G1, 1.00 GHz",
    ramDetail: "8 GB, DDR4 (On board 4GB +1 khe 4GB), 2666 MHz",
    ssdDetail: "SSD 512 GB M.2 PCIe, Hỗ trợ khe cắm HDD SATA",
    lcdDetail: "14 inch, Full HD (1920 x 1080)",
    vgaDetail: "Card đồ họa tích hợp, Intel UHD Graphics",
    inputDetail: "2 x USB 3.1, HDMI, USB Type-C",
    winDetail: "Windows 10 Home SL",
    settingDetail: "Vỏ nhựa - nắp lưng bằng kim loại, PIN liền",
    sizeDetail: "Dày 17.9 mm, 1.6 kg",
    years: 2019,
  },
  {
    id: 827,
    user_id: 27,
    category: 2,
    review: 2000,
    textBouns: "Nhận bộ quà hấp dẫn đến 8.5 triệu",
    sale: 0,
    priceSeller1: 11950000,
    price1: 33490000,
    textkm: "Hàng sắp về",
    core: "i5- 7200U",
    pin: 10,
    ram: 4,
    ssd: 256,
    name:
      "827 Combo 4 Hộp Khẩu Trang Y Tế 3Hmask 3 Lớp Quai Bản (Trắng) không đau tai",
    preorder: "Đặt hàng trước ngày 12/ 01",
    picAlt: "Samsung Galaxy S Mới 2",
    link:
      "https://res.cloudinary.com/cv-thav-herokuapp-com/image/upload/v1616828464/laptop/otgji5h257xhu6wwrz4j.jpg",
    categoryBeadcrumb: "Laptop",
    companyBeadcrumb: "Acer",
    cpuDetail: "Intel Core i5 Ice Lake, 1035G1, 1.00 GHz",
    ramDetail: "8 GB, DDR4 (On board 4GB +1 khe 4GB), 2666 MHz",
    ssdDetail: "SSD 512 GB M.2 PCIe, Hỗ trợ khe cắm HDD SATA",
    lcdDetail: "14 inch, Full HD (1920 x 1080)",
    vgaDetail: "Card đồ họa tích hợp, Intel UHD Graphics",
    inputDetail: "2 x USB 3.1, HDMI, USB Type-C",
    winDetail: "Windows 10 Home SL",
    settingDetail: "Vỏ nhựa - nắp lưng bằng kim loại, PIN liền",
    sizeDetail: "Dày 17.9 mm, 1.6 kg",
    years: 2019,
  },
  {
    id: 828,
    user_id: 27,
    category: 2,
    shipping: 1,
    review: 1000,
    textBouns: "Nhận bộ quà hấp dẫn đến 8.5 triệu",
    sale: 10,
    priceSeller1: 11950000,
    price1: 33490000,
    textkm: "",
    core: "i5- 7200U",
    pin: 10,
    ram: 4,
    ssd: 256,
    name:
      "828 Combo 4 Hộp Khẩu Trang Y Tế 3Hmask 3 Lớp Quai Bản (Trắng) không đau tai",
    preorder: "Đặt hàng trước ngày 12/ 01",
    picAlt: "Samsung Galaxy S Mới 2",
    link:
      "https://res.cloudinary.com/cv-thav-herokuapp-com/image/upload/v1616828464/laptop/siyvnleigbi6yhbmhtpi.jpg",
    categoryBeadcrumb: "Laptop",
    companyBeadcrumb: "Acer",
    cpuDetail: "Intel Core i5 Ice Lake, 1035G1, 1.00 GHz",
    ramDetail: "8 GB, DDR4 (On board 4GB +1 khe 4GB), 2666 MHz",
    ssdDetail: "SSD 512 GB M.2 PCIe, Hỗ trợ khe cắm HDD SATA",
    lcdDetail: "14 inch, Full HD (1920 x 1080)",
    vgaDetail: "Card đồ họa tích hợp, Intel UHD Graphics",
    inputDetail: "2 x USB 3.1, HDMI, USB Type-C",
    winDetail: "Windows 10 Home SL",
    settingDetail: "Vỏ nhựa - nắp lưng bằng kim loại, PIN liền",
    sizeDetail: "Dày 17.9 mm, 1.6 kg",
    years: 2019,
  },
  {
    id: 829,
    user_id: 27,
    category: 1,
    shipping: 1,
    review: 1000,
    textBouns: "Nhận bộ quà hấp dẫn đến 8.5 triệu",
    sale: 10,
    priceSeller1: 11950000,
    price1: 50490000,
    textkm: "",
    core: "i5- 7200U",
    pin: 10,
    ram: 4,
    ssd: 256,
    name:
      "829 Combo 4 Hộp Khẩu Trang Y Tế 3Hmask 3 Lớp Quai Bản (Trắng) không đau tai",
    preorder: "Đặt hàng trước ngày 12/ 01",
    picAlt: "Samsung Galaxy S Mới 2",
    link: "http://placehold.jp/200x200.png",
    categoryBeadcrumb: "Laptop",
    companyBeadcrumb: "Acer",
    cpuDetail: "Intel Core i5 Ice Lake, 1035G1, 1.00 GHz",
    ramDetail: "8 GB, DDR4 (On board 4GB +1 khe 4GB), 2666 MHz",
    ssdDetail: "SSD 512 GB M.2 PCIe, Hỗ trợ khe cắm HDD SATA",
    lcdDetail: "14 inch, Full HD (1920 x 1080)",
    vgaDetail: "Card đồ họa tích hợp, Intel UHD Graphics",
    inputDetail: "2 x USB 3.1, HDMI, USB Type-C",
    winDetail: "Windows 10 Home SL",
    settingDetail: "Vỏ nhựa - nắp lưng bằng kim loại, PIN liền",
    sizeDetail: "Dày 17.9 mm, 1.6 kg",
    years: 2019,
  },
  {
    id: 830,
    user_id: 27,
    category: 2,
    shipping: 1,
    review: 1000,
    textBouns: "Nhận bộ quà hấp dẫn đến 8.5 triệu",
    sale: 0,
    priceSeller1: 10000,
    price1: 90000,
    textkm: "Hàng sắp về",
    core: "i5- 7200U",
    pin: 10,
    ram: 4,
    ssd: 256,
    name:
      "830 Combo 4 Hộp Khẩu Trang Y Tế 3Hmask 3 Lớp Quai Bản (Trắng) không đau tai",
    preorder: "Đặt hàng trước ngày 12/ 01",
    picAlt: "Samsung Galaxy S Mới 2",
    link: "http://placehold.jp/200x200.png",
    categoryBeadcrumb: "Laptop",
    companyBeadcrumb: "Acer",
    cpuDetail: "Intel Core i5 Ice Lake, 1035G1, 1.00 GHz",
    ramDetail: "8 GB, DDR4 (On board 4GB +1 khe 4GB), 2666 MHz",
    ssdDetail: "SSD 512 GB M.2 PCIe, Hỗ trợ khe cắm HDD SATA",
    lcdDetail: "14 inch, Full HD (1920 x 1080)",
    vgaDetail: "Card đồ họa tích hợp, Intel UHD Graphics",
    inputDetail: "2 x USB 3.1, HDMI, USB Type-C",
    winDetail: "Windows 10 Home SL",
    settingDetail: "Vỏ nhựa - nắp lưng bằng kim loại, PIN liền",
    sizeDetail: "Dày 17.9 mm, 1.6 kg",
    years: 2019,
  },
  {
    id: 55,
    user_id: 27,
    category: 2,
    shipping: 1,
    review: 1000,
    textBouns: "Nhận bộ quà hấp dẫn đến 8.5 triệu",
    sale: 10,
    priceSeller1: 10000,
    price1: 98000,
    textkm: "Hàng sắp về",
    core: "i5- 7200U",
    pin: 10,
    ram: 4,
    ssd: 256,
    name:
      "55 Combo 4 Hộp Khẩu Trang Y Tế 3Hmask 3 Lớp Quai Bản (Trắng) không đau tai",
    preorder: "Đặt hàng trước ngày 12/ 01",
    picAlt: "Samsung Galaxy S Mới 2",
    link: "http://placehold.jp/200x200.png",
    categoryBeadcrumb: "Laptop",
    companyBeadcrumb: "Acer",
    cpuDetail: "Intel Core i5 Ice Lake, 1035G1, 1.00 GHz",
    ramDetail: "8 GB, DDR4 (On board 4GB +1 khe 4GB), 2666 MHz",
    ssdDetail: "SSD 512 GB M.2 PCIe, Hỗ trợ khe cắm HDD SATA",
    lcdDetail: "14 inch, Full HD (1920 x 1080)",
    vgaDetail: "Card đồ họa tích hợp, Intel UHD Graphics",
    inputDetail: "2 x USB 3.1, HDMI, USB Type-C",
    winDetail: "Windows 10 Home SL",
    settingDetail: "Vỏ nhựa - nắp lưng bằng kim loại, PIN liền",
    sizeDetail: "Dày 17.9 mm, 1.6 kg",
    years: 2019,
  },
  {
    id: 56,
    user_id: 27,
    category: 2,
    shipping: 1,
    review: 1000,
    textBouns: "Nhận bộ quà hấp dẫn đến 8.5 triệu",
    sale: 0,
    priceSeller1: 11950000,
    price1: 23490000,
    textkm: "Hàng sắp về",
    core: "i5- 7200U",
    pin: 10,
    ram: 4,
    ssd: 256,

    name:
      "56 Combo 4 Hộp Khẩu Trang Y Tế 3Hmask 3 Lớp Quai Bản (Trắng) không đau tai",
    preorder: "Đặt hàng trước ngày 12/ 01",
    picAlt: "Samsung Galaxy S Mới 2",
    link:
      "https://res.cloudinary.com/cv-thav-herokuapp-com/image/upload/v1616828465/laptop/ddvfhhdvinz7193e3hid.jpg",
    categoryBeadcrumb: "Laptop",
    companyBeadcrumb: "Acer",
    cpuDetail: "Intel Core i5 Ice Lake, 1035G1, 1.00 GHz",
    ramDetail: "8 GB, DDR4 (On board 4GB +1 khe 4GB), 2666 MHz",
    ssdDetail: "SSD 512 GB M.2 PCIe, Hỗ trợ khe cắm HDD SATA",
    lcdDetail: "14 inch, Full HD (1920 x 1080)",
    vgaDetail: "Card đồ họa tích hợp, Intel UHD Graphics",
    inputDetail: "2 x USB 3.1, HDMI, USB Type-C",
    winDetail: "Windows 10 Home SL",
    settingDetail: "Vỏ nhựa - nắp lưng bằng kim loại, PIN liền",
    sizeDetail: "Dày 17.9 mm, 1.6 kg",
    years: 2019,
  },
];

var myReducer = (state = initialState, action) => {
  switch (action.type) {
    case types.GETPRODUCT:
      return state;
    default:
      return state;
  }
};
export default myReducer;
